### ISSUE TITLE
大佬，cookie有获取教程吗，我拿浏览器的cookie一直都无法登陆

### ISSUE THREAD

**Issue by ZZLinvec** [MerlinCN/WeiboBot#2]
大佬，cookie有获取教程吗，我拿浏览器的cookie一直都无法登陆

**Comment by MerlinCN** [comment]
登录m.weibo.cn
按F12查看请求的cookies头
![image](https://user-images.githubusercontent.com/37311477/164148362-8580af0c-4673-4e52-a33a-5e398f0e50bb.png)

**Comment by MerlinCN** [comment]
登录m.weibo.cn
按F12查看请求头
![image](https://user-images.githubusercontent.com/37311477/164148500-c6a19f75-d1fd-48e6-9850-6c5380847dcd.png)

**Comment by ZZLinvec** [comment]
大佬，牛笔，感谢大佬，方便加给微信吗

**Comment by MerlinCN** [comment]
> 大佬，牛笔，感谢大佬，方便加给微信吗

加QQ吧 1249422707
