### ISSUE TITLE
大佬，能出个删除微博的功能吗？

### ISSUE THREAD

**Issue by wxmbaci** [MerlinCN/WeiboBot#3]
rt，我用你这个定时发微博，想发完就删除。
只想保活。

**Comment by MerlinCN** [comment]
抱歉现在才看到QuQ，这几天会加上

**Comment by wxmbaci** [comment]
哈哈，谢谢，我还想要群组私聊的功能，保持粉丝群活跃度。如果可以加上的话，非常感谢

**Comment by wxmbaci** [comment]
def getSTCode():
    ssl._create_default_https_context = ssl._create_unverified_context
    response1 = requests.post(url="https://m.weibo.cn/api/config", data=formdata, headers=headers)
    result = response1.content.decode('gbk').encode('utf-8').decode('unicode_escape')
    res = json.loads(result)
    print(res)
    print(res['data']['st'])
    return res['data']['st']
headers = {
    'authority': 'm.weibo.cn',
    'method': 'POST',
    'path': '/api/groupchat/send',
    'scheme': 'https',
    'accept': 'application/json, text/plain, */*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7',
    'content-length': '115',
    'content-type': 'application/x-www-form-urlencoded',
    'cookie': 'cookie',
    'mweibo-pwa': '1',
    'origin': 'https://m.weibo.cn',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'referer': 'https://m.weibo.cn/message/chat?gid=3797919239262069&name=m',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest'
}
# 发送消息脚本
# m.weibo.com
def get_timestamp():
    return int(time.time())  # 获取13位时间戳

def sendMessageGroup(content ):
    print(content)     
    sendMessageUrl = 'https://m.weibo.cn/api/groupchat/send'
    # 校验码
    st = getSTCode()
    formdata={
        'content': content,
        'gid': 3797919239262069,
        'st': st,
        '_spr': 'screen:1920x1080'
    }

    print(content)
    x=get_timestamp()
    ssl._create_default_https_context = ssl._create_unverified_context
    response = requests.post(url=sendMessageUrl, data=formdata, headers=headers)
    
    # result = response.content.decode('gbk').encode('utf-8').decode('unicode_escape')

    print("send msg success")


贴一下我以前写的，不知道微博有没有升级接口。

**Comment by MerlinCN** [comment]
已经在0.3.0中加入**del_weibo**
