### ISSUE TITLE
经常超时

### ISSUE THREAD

**Issue by kingxjs** [MerlinCN/WeiboBot#4]
![image](https://user-images.githubusercontent.com/17718227/190582059-9555c962-2309-4f91-91cb-1391d8765735.png)

**Comment by MerlinCN** [comment]
建议不要开启seleunim

**Comment by kingxjs** [comment]
不开启的话，也会报错
![image](https://user-images.githubusercontent.com/17718227/190589454-87502d1a-653d-4a18-b204-fbb35d71cfea.png)

**Comment by MerlinCN** [comment]
> 不开启的话，也会报错 ![image](https://user-images.githubusercontent.com/17718227/190589454-87502d1a-653d-4a18-b204-fbb35d71cfea.png)

已修复 非常抱歉

**Comment by kingxjs** [comment]
感谢🎉
