### ISSUE TITLE
点赞总是请求非法

### ISSUE THREAD

**Issue by kingxjs** [MerlinCN/WeiboBot#5]
网络错误!状态码:403
{"ok":0,"errno":"100006","msg":"\u8bf7\u6c42\u975e\u6cd5"}

**Comment by MerlinCN** [comment]
有必现情况吗？
我这里测试基本上很少见到，建议不要一天点赞太多次，会受到微博的限制

**Comment by kingxjs** [comment]
启动后第一个点赞是可以的，后面就都是请求非法（一般情况，也有几次开始就是请求非法）
![image](https://user-images.githubusercontent.com/17718227/192188499-9bf9e6af-d576-4821-98de-a310bdddb627.png)

**Comment by kingxjs** [comment]
目前看，应该是ip黑了

**Comment by kingxjs** [comment]
需要修改为移动端UA
