### ISSUE TITLE
大佬，请教两个问题

### ISSUE THREAD

**Issue by 3dian** [MerlinCN/WeiboBot#6]
1. bot.py的_scan_page方法中有这么一段
        for weibo in result["statuses"]:
            await self.chat_event()
   为什么在这个循环里，每次都要再去处理一次聊天信息呢？

2. 看到代码中用了async方法和await，但是在await后面跟的又是阻塞的request请求，这样的话，这个await是不是并没有起到协程的作用呢？

**Comment by MerlinCN** [comment]
第一个忘记删
第二个确实是那时候对协程没了解，所以导致了这种错误，有空可以pr

**Comment by MerlinCN** [comment]
谢谢提醒
